# Generated by Django 4.2.1 on 2023-09-17 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codeax1', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Courses',
            new_name='Course',
        ),
    ]
