# Generated by Django 4.2.1 on 2023-09-17 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codeax1', '0003_tag_prerequiste_learning'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Prerequiste',
            new_name='Prerequisite',
        ),
    ]
