# Generated by Django 4.2.1 on 2023-09-19 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeax1', '0005_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='extra_price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='learning',
            name='description',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='prerequisite',
            name='description',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='tag',
            name='description',
            field=models.CharField(max_length=40),
        ),
    ]
