# Generated by Django 4.2.1 on 2023-09-20 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeax1', '0007_remove_course_extra_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='slug',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_id',
            field=models.CharField(max_length=50),
        ),
    ]
