# Generated by Django 4.2.1 on 2023-09-23 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codeax1', '0010_usercourse_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
